name: pySpark CI
on:
  push:
    paths:
    - 'pySpark/**'
  pull_request:
    paths:
    - 'pySpark/**'
jobs:
  pySpark-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
