name: PySpark CI
on:
  push:
    paths:
    - 'pySpark/**'
  pull_request:
    paths:
    - 'pySpark/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install dependencies
      run: |
        sudo apt-get install openjdk-8-jdk-headless -qq > /dev/null
        wget -q https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz
        tar xf spark-3.2.0-bin-hadoop3.2.tgz
        pip install -q findspark

    - name: Set up environment variables
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        echo "SPARK_HOME=$GITHUB_WORKSPACE/spark-3.2.0-bin-hadoop3.2" >> $GITHUB_ENV

    - name: Run PySpark script
      run: |
        python pySpark/index.py