name: R CI
on:
  push:
    paths:
    - 'R-programs/**'
  pull_request:
    paths:
    - 'R-programs/**'
jobs:
  R-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'
    - name: Install dependencies
      run: |
        Rscript -e "install.packages('ggplot2', dependencies = TRUE, repos = 'http://cran.rstudio.com/')"
    - name: Check R scripts
      run: |
        Rscript R-programs/linear-regression/index.r
